- hosts: all
  #   become: true

  tasks:
    - name: create a docker image with deployed waf file
      command: docker build -t yangdm9378/cicd-pjt-ansible .
      args:
        chdir: /root

    - name: push the image on Docker Hub
      command: docker push yangdm9378/cicd-pjt-ansible
      ignore_errors: yes
    - name: remove the docker image from the ansible server
      command: docker rmi yangdm9378/cicd-pjt-ansible
      ignore_errors: yes
